src/main.py, tests/fixtures/response_data.py
A good chunk of the compute done by the Edge Proxy is JSON marshalling and unmarshalling. When returning plain dictionaries, FastAPI inspects every individual item inside to make sure it's serializable. We know it is in this case, as if it weren't client SDKs would not work.
From the docs:
> For large responses, returning a Response directly is much faster than returning a dictionary.
>
> This is because by default, FastAPI will inspect every item inside and make sure it is serializable with JSON, using the same JSON Compatible Encoder explained in the tutorial. This is what allows you to return arbitrary objects, for example database models.
>
> But if you are certain that the content that you are returning is serializable with JSON, you can pass it directly to the response class and …
=> Return JSONResponse(dict) instead of dict

src/main.py
Allows an extra 30 seconds per environment to sync before assuming the data is stale and the instance unhealthy.
As designed before, the health check didn't allow any time for environments to sync before marking the instance as unhealthy. This could happen if a health check ping arrived during the environment refresh, meaning the `api_poll_frequency` had elapsed, but its refresh had not yet finished. It'd be marked as stale when it was just waiting.
=> Allow time for environments to sync

src/cache.py, src/exceptions.py, src/main.py, tests/test_cache.py, tests/test_main.py
Use an internal exception type and a dedicated exception handler, ensuring unknown key errors are correctly returned as 403.
=> Improve handling of unknown key errors

requirements.in, requirements.txt, src/cache.py, src/main.py, tests/test_cache.py
_#74 should be merged before this one. If it's not accepted, I should adjust this one accordingly._
---
Continuation of the performance work started in #75. A good chunk of the compute done by the Edge Proxy is JSON marshalling and unmarshalling, and having a more performant library has an impact.
Serving Todoist and Twist on a few ECS instances with 4 vCPUs shows:
- Reduction in average CPU usage of ~1%
- Reduction in p99 latency of ~5%
- Increased throughput by ~8%
With #75 and this one, an ECS instance with 4 vCPU can now handle 3000 requests per minute without noticeable variation to p99 latency.
=> Adopt orjson

src/main.py
We've seen a 6x reduction in traffic from enabling this middleware:
Without any impact to CPU utilization:
Straight out of the [documentation](https://fastapi.tiangolo.com/advanced/middleware/#gzipmiddleware).
=> Enable gzip-compressing middleware

src/environments.py, src/exceptions.py, src/main.py
When using endpoint caches, for large payload sizes, the Edge Proxy would throw an exception but return a 200 OK response with an empty body. Looking in the logs, I determined the cause was 
```
h11._util.LocalProtocolError: Too much data for declared Content-Length
```
When I compared a cached response with a non-cached response, I could see that the cached response was setting a `Content-Length` header about 1/4 of the size of the non-cached response. 
I haven't investigated the cause of this too deeply as it seems to be buried deep in the internals of `lru_cache` and/or `ORJSONResponse` code. Instead, I have abstracted the serialization back to the `main` module and out of the environment service which, to me, feels cleaner anyway. It adds a small amount of processing back to the …
=> fix: `Too much data for declared Content-Length` error when endpoint caches enabled

CONTRIBUTING.md, src/settings.py
- add config file location fetching from environment variable (`CONFIG_PATH`). Defaulting to `config.json` (previous value) if environment variable is not defined.
- preserves backwards compatibility by not requiring `CONFIG_PATH` to be defined
=> feat: allow config file to be defined via environment variable

src/edge_proxy/logging.py, src/edge_proxy/main.py, src/edge_proxy/settings.py
Logging config now accepts the `override` key, under which Python-compatible logging settings can be provided. The overridden settings take precedence over logging settings like `enable_access_log`, etc. `default` handler that utilises the `log_format` setting can be used in the override. For example, to log everything a file, one can set up own file handler and assign it to the root logger:
```json
"override": {
"handlers": {
"file": {
"level": "INFO",
"class": "logging.FileHandler",
"filename": "foo.log",
"formatter": "json"
}
},
"loggers": {
"": {
"handlers": [
"file"
],
"level": "INFO",
"propagate": true
}
}
}
```
Or, log access logs to file in generic format while logging everything else to stdout in json:
```json
"override": {
"handlers": {
"file": {
"level": "INFO",
"class": …
```
=> feat: Customised logging

src/edge_proxy/health_check/responses.py, src/edge_proxy/server.py, src/edge_proxy/settings.py, tests/test_server.py
This PR looks to solve #120. 
It does so by making certain aspects of the health check configurable, with the bear minimum health check being to confirm that the environment document has been updated at some point.
=> feat: make health check configurable

src/edge_proxy/server.py, src/edge_proxy/settings.py, tests/test_server.py
Based on a conversation with @rolodato on https://github.com/Flagsmith/flagsmith/pull/4580, I have updated the settings added in #122 to remove the boolean setting used to configure the essentially 'infinite grace period' and replaced it with the option to set the grace period to null. In order to help with the readability though, I have also renamed the grace period field. 
Note: since the documentation has not been released for the original settings, I plan to release this as a minor update with a mention in the notes about the breaking settings changes.
=> feat: remove unnecessary setting `health_check.count_stale_documents_as_failing`

.github/workflows/docker-publish-image.yml
Updates the docker workflow to use the new org-level variable / secret. 
The new org level variable / secret use a PAT from the `flagsmithdocker` user in our dockerhub account.
=> ci: use new org-level dockerhub token

src/edge_proxy/environments.py, tests/test_environments.py
As suggested by @matthewelwell in [this issue](https://github.com/Flagsmith/edge-proxy/issues/129), this workaround allows for adding server keys to the edge proxy that will bypass filtering of server-side only features, e.g.
```
"environment_key_pairs": [
{
"client_side_key": "abc123",
"server_side_key": "ser.def456"
},
{
"client_side_key": "ser.def456",
"server_side_key": "ser.def456"
}
],
```
Tests added to ensure that the three places that use filter_out_server_key_only_feature_states are covered and confirmed to be returning the feature that is filtered out for a client side key.
=> feat: Bypass server-side filtering for server keys

src/edge_proxy/server.py, tests/test_server.py
This adds the `GET /api/v1/identities` endpoint, which accepts only an identifier via query parameters and no traits. It is used by some SDKs ([example: JS](https://github.com/Flagsmith/flagsmith-js-client/blob/5cd31ca06b1dac52932a2d4e81dc889d5eb6ebf2/flagsmith-core.ts#L206)) when traits are not being used.
=> feat: Add GET /api/v1/identities endpoint

src/edge_proxy/settings.py
Related to [this issue](https://github.com/Flagsmith/edge-proxy/issues/140).
The purpose is to prevent the application from hard crashing when unrecognised environment variables are provided.
=> fix: ignore unknown env vars

README.md, src/edge_proxy/settings.py
```
~/s/f/edge-proxy►rye run edge-proxy-render-config                 (feat/get-identities-endpoint) 13:20
/Users/rolodato/source/flagsmith/edge-proxy/.venv/lib/python3.12/site-packages/pydantic/main.py:398: UserWarning: Pydantic serializer warnings:
Expected `url` but got `str` - serialized value may not be as expected
return self.__pydantic_serializer__.to_json(
{
"environment_key_pairs": [
{
"server_side_key": "ser.environment_key",
"client_side_key": "environment_key"
}
],
"api_url": "https://edge.api.flagsmith.com/api/v1",
"api_poll_frequency_seconds": 10,
"api_poll_timeout_seconds": 5,
"allow_origins": [
"*"
],
"logging": {
"enable_access_log": false,
"log_format": "generic",
"log_level": "INFO",
"log_event_field_name": "message",
"colours": false,
"override": {}
},
"server": { …
```
=> fix: Warning when running edge-proxy-render-config

src/edge_proxy/settings.py, tests/conftest.py, tests/test_server.py, tests/test_settings.py
This is the behaviour when running the Edge Proxy with no configuration:
```
% docker run --rm flagsmith/edge-proxy
2025-03-14T18:43:17.793837Z [info     ] Started server process [1]     [uvicorn.error]
2025-03-14T18:43:17.793915Z [info     ] Waiting for application startup. [uvicorn.error]
2025-03-14T18:43:17.795896Z [info     ] Application startup complete.  [uvicorn.error]
2025-03-14T18:43:17.796444Z [info     ] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit) [uvicorn.error]
2025-03-14T18:43:18.033553Z [info     ] HTTP Request: GET https://edge.api.flagsmith.com/api/v1/environment-document/ "HTTP/1.1 401 Unauthorized" [httpx]
2025-03-14T18:43:18.034012Z [error    ] error_fetching_document        [edge_proxy.environments] client_side_key=environment_key
Traceback (most …
```
=> feat: Immediately exit if configuration is missing or invalid

src/edge_proxy/main.py, src/edge_proxy/settings.py, tests/test_server.py
This enables Uvicorn's `--proxy-headers` option: https://www.uvicorn.org/settings/#http
This is useful when enabling Uvicorn access logs, if we want to see the actual client IPs and not just a loopback address.
This option must be used in combination with the `FORWARDED_ALLOW_IPS` environment variable. I chose not to add it to the config file for simplicity.
=> feat: Add `server.proxy_headers` option

Dockerfile, src/edge_proxy/settings.py
In https://github.com/Flagsmith/edge-proxy/pull/148, we changed the config behaviour so that invalid or missing configurations are rejected with an error. This effectively broke `edge-proxy-render-config` when called without environment variables, which also broke the Docker build: https://github.com/Flagsmith/edge-proxy/actions/runs/14308473957/job/40097587318
Because a config file is no longer required, and we don't need an empty/placeholder config file to show a useful error message, we now don't render a config file at all in the Docker build. If the config file is not found, we now log a message and don't fail with an error. This does not break customers who are mounting/copying their config file into the Edge Proxy container.
This is what running the container with no environment …
=> fix(ci): Don't render config in Dockerfile

src/edge_proxy/environments.py, tests/fixtures/response_data.py, tests/test_environments.py
Adds support for https://github.com/Flagsmith/flagsmith/pull/5283
Example log output:
```
❯ rye run edge-proxy-serve
2025-04-29 19:26:49 [info     ] Loaded configuration from config.json
2025-04-29 19:26:49 [info     ] Loaded configuration from config.json
2025-04-29T22:26:49.666581Z [info     ] Started server process [50212] [uvicorn.error]
2025-04-29T22:26:49.666789Z [info     ] Waiting for application startup. [uvicorn.error]
2025-04-29T22:26:49.701255Z [info     ] HTTP Request: GET http://localhost:8000/api/v1/environment-document/ "HTTP/1.1 200 OK" [httpx]
2025-04-29T22:26:49.701813Z [info     ] Application startup complete.  [uvicorn.error]
2025-04-29T22:26:49.702157Z [info     ] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit) [uvicorn.error] …
```
=> feat: Set If-Modified-Since header for environment document requests

src/edge_proxy/server.py
The httpx client was not configured to follow redirects, which caused issues when the Flagsmith API returned 307 Temporary Redirect responses.
Added `follow_redirects=True` to the httpx.AsyncClient configuration in `src/edge_proxy/server.py`.
- Modified `src/edge_proxy/server.py` to enable redirect following
- All existing tests continue to pass
- Code quality checks (ruff linting/formatting) pass
- ✅ All 46 tests pass
- ✅ Pre-commit hooks pass
- ✅ No breaking changes to existing functionality
This change ensures proper handling of redirect responses from the Flagsmith API, improving reliability when the API returns 307 status codes.
=> fix: enable follow_redirects for httpx client to handle 307 status codes
